### ISSUE TITLE
Category and Tag Taxonomy

### ISSUE THREAD

**Issue by mongmedia** [YaleDHLab/dhlab-site#112]
Most of the events / projects / news items have been roughed in. We are now at a point where tags can be applied on these posts based on a taxonomy that establishes our DHLab standards for categories and tags. 

Let's start a thread that establishes the taxonomy and review the legacy tags and clarify what is useful to keep and what should be modified in order to strengthen the framework we've set up here that delineates the four buckets laid out on the website and also the focus of the DHLab. 

PROJECTS
Categories:  
- Network Analysis
- Visual Analysis
- Textual Analysis
- Geospatial Analysis

Tags:
- Crowdsourced Transcription
- Virtual Reality
- Historical mapping
- Text Encoding Initiative
- Neural Networks
...

EVENTS
Categories:
- Workshops
- Talks
- Office Hours
- Meetups
- Symposia
- On Campus
...
Tags:
- Network Analysis
- Visual Analysis
- Textual Analysis
- Geospatial Analysis
- Coding
...

NEWS
Categories:
- Student Jobs
- Opportunities (such as grant deadlines)
- In the Field (Is there a better way of referencing news about Yale people in the greater DH Field?)
- Announcements
...

**Comment by cderose** [comment]
For project tags, we may want to generalize "Crowdsourced Transcription" to just "Crowdsourcing" so that it can encompass current projects as well as future crowdsourcing ones that might not have a transcription component to them. We could even split the tag into two, if filtering by transcription projects could be helpful for some users: "Crowdsourcing" + "Transcription". 

I was thinking about changing "Historical Mapping" to just "Mapping" for the same reason as above, but if users will be able to filter by category as well as tag, then all mapping projects would be selected with "Geospatial Analysis," making a "Mapping" tag redundant. For that reason, I'd say let's keep "Historical Mapping".

For "TEI," I'm not sure we need that tag for the projects bucket. Were you thinking of Robin's project, or is there another I'm not thinking of that would benefit from having the tag?

**Comment by cderose** [comment]
For news, that's a good question about "In the Field." After a few searches with that tag, people should catch on, so we could go with that. For something more immediately recognizable, maybe something along the lines of "DH News", "Broader DH News", "General DH Announcements"...
