### ISSUE TITLE
Footer links

### ISSUE THREAD

**Issue by mongmedia** [YaleDHLab/dhlab-site#153]
Hi, Team:

Can we confirm the links that we want to appear in the website footer? It currently includes digital scholarship links there under "On Campus" -- please suggest any edits that make sense there.

**Comment by duhaime** [comment]
I'd prioritize Github over one of the other social media sites, as the others have similar content...

**Comment by cderose** [comment]
@mongmedia, could you include a screenshot of the area in question just to make sure I'm looking at the most recent version?

**Comment by duhaime** [comment]
Here's the footer @cderose!

For On Campus I'd propose CCAM, YINS, CTL, and Stat Lab

![screen shot 2017-11-01 at 12 36 51 pm](https://user-images.githubusercontent.com/4801116/32285668-5ca5a7b6-bf01-11e7-8d0f-f3cf6f97d6ef.png)

**Comment by cderose** [comment]
Thanks very much, @duhaime! 

I second Doug's suggestion of CTL. I'd also suggest swapping CSSSI for StatLab specifically, though I suppose they'll be in Digital Scholarship. We might also add YCRC. CCAM also comes to mind. Is there a different page somewhere on the website where we might direct people to a longer list of on campus resources so that the list in the footer can remain pared down? 

For social media/extras, my ranking would be like: Twitter, GitHub, Instagram, Facebook. If we were to remove one from that list, I'd remove Facebook.

**Comment by duhaime** [comment]
The extant links are not active. I'm going to close this and we can reopen if we want to change the links.

**Comment by mongmedia** [comment]
@duhaime -- can we reopen and I can work on applying the links to the footer this week? We also need to figure out if we want to list a phone number in the footer and if so, which number?

**Comment by cderose** [comment]
@mongmedia, for now I'd say let's just have the dhlab's email address. We might revisit adding a phone number when we're in the Franke room.

**Comment by duhaime** [comment]
I'm happy to leave this open if you want to make changes @mongmedia...
