### ISSUE TITLE
Archive Page fixes

### ISSUE THREAD

**Issue by mongmedia** [YaleDHLab/dhlab-site#298]
For the Archive project page there are a couple issues:

- [x] If the featured project is also show in the include below, would there be a way to detect the redundancy and skip over it in the include?

- [x] For the include, how would it be possible to skip the word "overview" in the 3 text blurbs?

Sample here:
http://127.0.0.1:4000/dhlab-site/projects/athena.html

Thanks, Monica

**Comment by mongmedia** [comment]
Hi, @duhaime - Would you be able to look at this issue before launch? I'm not sure how to hide an archived project from the bottom include if it happens to appear on the same page as that project.

**Comment by duhaime** [comment]
@mongmedia Sure thing! The trick here is to create an empty list into which we'll add projects that aren't identical to the page's project. To do so, we can loop over all projects, compare the title of each to the title of the current project, and if they're different add the current value in the loop to the whitelisted list of projects:

so instead of this:
```
{% assign bottom_items = site.projects | limit: 3 %}
```

we can do this:
```
{% assign items = '' | split: '' %}
{% for item in site.projects %}
  {% if item.title != page.title %}
    {% assign items = items | push: item %}
  {% endif %}
{% endfor %}

{% assign bottom_items = items | limit: 3 %}
```
