### ISSUE TITLE
Display dates of past events

### ISSUE THREAD

**Issue by cderose** [YaleDHLab/dhlab-site#508]
@mongmedia, do you think it would look ok if we displayed dates on the [past events](http://dhlab.yale.edu/events.html) images like we do for [past workshops ](http://dhlab.yale.edu/resources/workshops.html)? I can take care of implementing it, but I wanted your input first.

**Comment by mongmedia** [comment]
Aesthetically, it helps to differentiate past events from new ones by not having the dates on and also looks less busy, particularly because we are displaying many past events all together. However, if you find that users are searching past events by date, I would do it if that helps with better engagement with event info on the site. Hope that helps.

**Comment by duhaime** [comment]
Mockup for dates to be displayed on hover of grid item on events route:

<img width="183" alt="thumbnail_Screenshot 2019-08-20 10 11 14" src="https://user-images.githubusercontent.com/4801116/63357604-afb4f380-c337-11e9-806b-ba8fb3b65e84.png">
